# Generated by Django 5.2.4 on 2025-09-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='Google profile picture URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
