# Generated by Django 5.2.4 on 2025-09-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_google_id_profile_profile_picture_url_and_more'),
    ]

    operations = [
    ]
